### ISSUE TITLE
404 Not found BIG TIME

### ISSUE THREAD

**Issue by yldbouk** [SamyPesse/How-to-Make-a-Computer-Operating-System#110]
I don't know how to explain but either ubuntu deleted some things from their archive, or the link is incorrect. Take a look:
[Item Install Log.txt](https://github.com/SamyPesse/How-to-Make-a-Computer-Operating-System/files/345751/Item.Install.Log.txt)

**Comment by sniperLx** [comment]
I have the same problem.  who can give a idea to solve it .

**Comment by indrakaw** [comment]
Have you tried proxy network it? @yldbouk

**Comment by Wachiwi** [comment]
It seems you try to fetch updates for Ubuntu Lucid Lynx (10.04). But its support expired at the 29 April 2015 for servers. So Lucid packages aren't available anymore. Look [here](http://us.archive.ubuntu.com/ubuntu/dists/) for active distributions.
