### ISSUE TITLE
Translate into Korean

### ISSUE THREAD

**Issue by JunoJunho** [SamyPesse/How-to-Make-a-Computer-Operating-System#116]
Hi, I want to translate this fantastic project.

Is there any process I have to follow?

**Comment by Rumo-Arf** [comment]
Me.

https://github.com/Rumo-Arf/How-to-Make-a-Computer-Operating-System

**Comment by JunoJunho** [comment]
@Rumo-Arf  Did you get any approval from the author?

**Comment by Rumo-Arf** [comment]
Nope, but #89 shows that translating to another language won't be problem may be...

**Comment by carlosdelfino** [comment]
refer to https://toolchain.gitbook.com/languages.html for diretory layout.

We will unite in a single repository to do a standardized translation each for your language.

I am waiting for the author's reply at #126

**Comment by Rumo-Arf** [comment]
Nice, I am new to gitbook.

**Comment by carlosdelfino** [comment]
I think we need to wait for the author ( @SamyPesse )´s response, 

But without a doubt the next step is to create a common repository for all, an organization where the project and everything related will be placed.

I suggest there are 3 repositories,

* One for the project site one entry page. (Gh-pages)
* One for the text of the book and its translations
* And finally one with the sample book sources.

What do you think?
We could open an issue in this new repository to discuss this.
