### ISSUE TITLE
"make run" fail

### ISSUE THREAD

**Issue by yogeshbalan** [SamyPesse/How-to-Make-a-Computer-Operating-System#125]
Building Kernel
make -C ./kernel
make[1]: Entering directory '/home/yogesh/Development/How-to-Make-a-Computer-Operating-System/src/kernel'
nasm   -f elf -o  -c arch/x86/start.asm -o  arch/x86/start.o
make[1]: nasm: Command not found
Makefile:64: recipe for target 'arch/x86/start.o' failed
make[1]: *** [arch/x86/start.o] Error 127
make[1]: Leaving directory '/home/yogesh/Development/How-to-Make-a-Computer-Operating-System/src/kernel'
Makefile:10: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by janisozaur** [comment]
`make[1]: nasm: Command not found`

**Comment by Coretool** [comment]
Looks like you have to install `nasm`

**Comment by yogeshbalan** [comment]
Thanks @janisozaur and @Coretool
