### ISSUE TITLE
why my lucid32 cannot install tools like nasm, make, build-essential, grub and qemu??

### ISSUE THREAD

**Issue by LeoChen008** [SamyPesse/How-to-Make-a-Computer-Operating-System#155]
I added the lucid32 box and this is my kernel version.
**Linux lucid32 2.6.32-38-generic #83-Ubuntu SMP Wed Jan 4 11:13:04 UTC 2012 i686 GNU/Linux**
But when I want to install tools by apt-get,it is failed.
**Err http://us.archive.ubuntu.com/ubuntu/ lucid/main make 3.81-7ubuntu1
  404  Not Found**
Is my apt-get too old or some other issues??

**Comment by SnailShea** [comment]
Try `apt-get update && apt-get upgrade` first
