### ISSUE TITLE
Where are PDF, Mobi and ePub versions?

### ISSUE THREAD

**Issue by BrianG61UK** [SamyPesse/How-to-Make-a-Computer-Operating-System#163]
Where are the PDF, Mobi and ePub versions?

**Comment by sissioy** [comment]
The official interpretation of the new version of gitbook is as follows:

>PDF and other ebook formats exports ？ The new version of GitBook no longer supports exporting to PDF and other ebooks format. A lot of rich-content does not translate well from the Web to PDF. GitBook will expose a developer API for people to consume and extend their content. It is not excluded that someone build a PDF export tool using the API, but it will not be officially supported. See the section about offline access if this is the part you cared about.

And if you still want to convert to pdf/mobi/epub format, you can google ebook-convert (cause I only found a tutorial of Chinese version)
Here is the link:
[https://www.mapull.com/gitbook/comscore/extend/pdf.html](https://www.mapull.com/gitbook/comscore/extend/pdf.html)
