### ISSUE TITLE
Chapter-2：make run have problem

### ISSUE THREAD

**Issue by ghost** [SamyPesse/How-to-Make-a-Computer-Operating-System#174]
When I try to run the make run command in Chapter 2, the cmd window jumps to qume and stops at boot from hard disk.
![image](https://user-images.githubusercontent.com/50431473/162974574-61476a8e-d1de-4f1e-a041-c09d3a318d56.png)
vm OS: Ubuntu 14.04.6 LTS (GNU/Linux 3.13.0-170-generic i686)
host OS: win 10
vagrant: Installed Version: 2.2.19
              Latest Version: 2.2.19
virtualbox:6.1

**Comment by ghost** [comment]
i know where i am wrong.I should use the fdisk tool to initialize c.img according to the actual situation of my disk.
![image](https://user-images.githubusercontent.com/50431473/162982486-e4fcf641-57ad-40b5-94dc-164289626a54.png)

**Comment by Wisam907** [comment]
> i know where i am wrong.I should use the fdisk tool to initialize c.img according to the actual situation of my disk. ![image](https://user-images.githubusercontent.com/50431473/162982486-e4fcf641-57ad-40b5-94dc-164289626a54.png)

Can you explain it more? Now I meet the same question and don't know how to correct it. thank you!!!

**Comment by jere-fade** [comment]
> i know where i am wrong.I should use the fdisk tool to initialize c.img according to the actual situation of my disk. ![image](https://user-images.githubusercontent.com/50431473/162982486-e4fcf641-57ad-40b5-94dc-164289626a54.png)

same problem, can you explain details about fdisk settings?
