### ISSUE TITLE
BIOS stuck at booting from harddisk

### ISSUE THREAD

**Issue by vyasgiridhar** [SamyPesse/How-to-Make-a-Computer-Operating-System#99]
The BIOS is stuck at booting from the hard disk for a long time.

**Comment by aswinmohanme** [comment]
Yep Same Problem Here :(

**Comment by vyasgiridhar** [comment]
While digging through the make file, I found that the bash script for initialising the IMG contained qemu-img which was not available and needs to be installed 

The package name is qemi-utils.

**Comment by huanzhang** [comment]
@vyasgiridhar I did't find package qemu-utils from lucid's repo http://old-releases.ubuntu.com/ubuntu/
